### ISSUE TITLE
socks5 proxy support?

### ISSUE THREAD

**Issue by xMaxximum** [mrcyclo/CaptureProxy#1]

**Comment by mrcyclo** [comment]
Maybe in the future. My next intention is to support HTTP2.

**Comment by xMaxximum** [comment]
Very nice project though! I'd help you implement it but don't currently have the time.
Project structure seems a bit messy right now

**Comment by mrcyclo** [comment]
I agree that the project structure is quite messy. I worked on it in my free time and I'm not specialized in C#. I hope you can restructure the project when you have free time so that I can learn from it. Thanks.
